# Generated by Django 3.2.9 on 2022-09-07 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='marks/')),
                ('desctiption', models.CharField(max_length=500)),
                ('gravit', models.IntegerField()),
                ('date', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('mymark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='AiMark.mymark')),
            ],
        ),
    ]
